### ISSUE TITLE
Tests related files should not be bundled into deployment

### ISSUE THREAD

**Issue by songgao** [virgo-agent-toolkit/rackspace-monitoring-agent#448]
Currently both `rackspace-monitoring-agent` and `make test` target uses a same bundle (`rackspace-monitoring-agent-bundle.zip`) built from `make_bundle` target. It would be nice to have a test bundle target just for testing, which contains tests related stuff, and a release bundle that only have lua scripts required to run. This way we can keep the released bundle clean/minimal.

**Comment by kaustavha** [comment]
Lit excludes the tests directory when bundling.

**Comment by songgao** [comment]
It's really a pleasure to see such an an old issue closed. Thanks @kaustavha !
