### ISSUE TITLE
[FREEBSD] Build fails because of GCC dependency

### ISSUE THREAD

**Issue by unkletee** [virgo-agent-toolkit/rackspace-monitoring-agent#537]
FreeBSD 10 release has ditched GCC (completely - it's not even in the base system anymore) in favour of LLVM/CLANG. Because of that build on this target OS fails with this error (after some time build was running):

--- CUT ---
  COPY /opt/virgo-0.1.9/out/Debug/jit
  ACTION _opt_virgo_0_1_9_base_bundle_gyp_bundle_h_target_bundle /opt/virgo-0.1.9/out/Debug/obj/gen/bundle.h
  TOUCH /opt/virgo-0.1.9/out/Debug/obj.target/base/bundle.zip.embed.stamp
  TOUCH /opt/virgo-0.1.9/out/Debug/obj.target/base/bundle.zip.stamp
  AR(target) /opt/virgo-0.1.9/out/Debug/obj.target/base/deps/libarchive.a
  AR(target) /opt/virgo-0.1.9/out/Debug/obj.target/base/deps/liblua_sigar.a
  LINK(target) /opt/virgo-0.1.9/out/Debug/minilua
lockf: g++: No such file or directory
gmake[1]: *** [/opt/virgo-0.1.9/out/Debug/minilua] Error 1
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: Leaving directory `/opt/virgo-0.1.9/out'
gmake: *** [all] Error 2
--- CUT ---

Installing GCC is not a proper solution. There is a reason why FreeBSD 10 release ditched GCC and there is a reason why you get whole pile of warnings while trying to install GCC on this distro from ports.

**Comment by dt1973** [comment]
Thanks for that fix @rphillips ;)
