### ISSUE TITLE
Add a hostinfo endpoint which tracks out of date packages

### ISSUE THREAD

**Issue by alex** [virgo-agent-toolkit/rackspace-monitoring-agent#579]
This could show all apt-get packages (on Ubuntu) which have un-applied updates. Even cooler would be if it could track which stream they come from (i.e. security vs. general updates).

**Comment by kaustavha** [comment]
The packages hostinfo check now does this. Returns the version string for any and all packages, its upto the upstream consumer to discern wether theyre out of date or their streams.
