### ISSUE TITLE
Report Host Info Types that are only supported by the Agent on the particular OS

### ISSUE THREAD

**Issue by rjemanuele** [virgo-agent-toolkit/rackspace-monitoring-agent#583]
We have a thought that the list of host info types reported by the agent to the AEP should only be the types supported by this agent on this OS.  Discuss.....

**Comment by kaustavha** [comment]
We have something that satisfies this requirement now i believe. 
```
local Info = require('./base').HostInfo
function Info:getPlatforms()
  return {'linux'} -- or 'windows' or 'darwin' or all three
end
```
