### ISSUE TITLE
Create Apache VHost Check

### ISSUE THREAD

**Issue by wolfdancer** [virgo-agent-toolkit/rackspace-monitoring-agent#597]
The Apache check does not display the status of the virtual hosts.  http://blog.e-shell.org/132
An alternative would be to enhance the apache check to have the virtual hosts status. The risk is the variation of the number of metrics, and how to map the host name as part of the metrics locator.

**Comment by kaustavha** [comment]
apache2 hostinfo does check vhosts now. Due to the uniqueness of vhost data it makes sense to have it in an ondemand call like hostinfo vs a recurring 'check'.
