### ISSUE TITLE
Add process check

### ISSUE THREAD

**Issue by rphillips** [virgo-agent-toolkit/rackspace-monitoring-agent#622]
We should add a native agent check that inspects resource use by a program (1 or more processes).
It should:
1. Take a regex (or similar pattern) that can be used to match a command as a parameter to the check
2. The check should find all processes matching the pattern supplied, and aggregate metrics across them (ie, we don't report metrics for each individual process).
In terms of metrics, we should ideally report at least CPU and memory use, as well as how many processes were aggregated.
Lets try to make this work on Windows too.

**Comment by Speeddymon** [comment]
With Apache supporting PHP-FPM in 2.4 (RHEL7 and derivatives), this will be useful to track PHP memory usage across processes. I would like to see this.
It would be handy to be able to track threads created as well, though I think that's probably discussion best suited for a new ticket.
