### ISSUE TITLE
Add the ability to use HostInfo data as a Check

### ISSUE THREAD

**Issue by rjemanuele** [virgo-agent-toolkit/rackspace-monitoring-agent#645]
There is a wide variety of data available using the HostInfo system within the agent.  People have expressed interest in using HostInfo data as check data.

Pros:
- HostInfo data can then be treated as metrics and stored long-term
- Changes to HostInfo has the potential to be alarmed on

Cons:
- Some HostInfo data does not map well to a check format

**Comment by eddywashere** [comment]
Would love to get processes logged so that way when some other metric is alerted on, I can associate that information with the processes running at that point in time.

**Comment by rjemanuele** [comment]
I was just talking with @wolfdancer about this.  We're going to have a discussion with the agent, ele core and any other team working with us to review this idea.  One thought that came up is hostinfo becoming a "check" with a single snapshot of data (basically no metrics history).  This gives us the ability to pass parameters to hostinfo "check" and alarm on them.  Throwing ideas out and seeing what sticks.

**Comment by wolfdancer** [comment]
@eddywashere: the use case you describe requires integration with the monitoring service, and there are different ways to achieve that.  For example, as part of the notification implementation on the monitoring service, it can call into the agent host info, retrieve and store the data. In this way, the host info data would be close to the time of the alert.

What @rjemanuele described is still accurate. Just that it does not have to be a blocked for the case you described.

**Comment by rillip3** [comment]
I tried these changes, but couldn't get berks to resolve dependencies anymore.

**Comment by rjemanuele** [comment]
Obsolete
