### ISSUE TITLE
Is it possible to have IP address returned as part of the network check target response?

### ISSUE THREAD

**Issue by wolfdancer** [virgo-agent-toolkit/rackspace-monitoring-agent#672]
I found myself typing "ifconfig" when setting up the network checks just to figure out which one to pick. If the IP addresses are returned as part of the target response, this will eliminate another need for accessing the box manually.

**Comment by rphillips** [comment]
It's a good idea and easy to change, but it breaks the current API because the list is returned in a flat array of names ```["eth0", "br0", ...]```.
