### ISSUE TITLE
Have to switch to "master" branch to build after I clone the project

### ISSUE THREAD

**Issue by wolfdancer** [virgo-agent-toolkit/rackspace-monitoring-agent#697]
I am not sure why but I have to type "git co master" after I clone this project. Otherwise the command "configure & make" does not work because the files don't exist.

**Comment by rjemanuele** [comment]
as all the development is being done against the luvi-up branch, we have made that the default branch.    it simplifies making PRs greatly.  master still exists for legacy changes and bug fixes.  when on the luvi-up branch all that is needed is to run "make".

**Comment by rphillips** [comment]
Closing... the default branch is the luvi-up branch like Rob mentioned.
