### ISSUE TITLE
Trim the agent configuration file before parsing it

### ISSUE THREAD

**Issue by wolfdancer** [virgo-agent-toolkit/rackspace-monitoring-agent#718]
Brian from Stratus provided the following feedback to trim the lines in agent config file. I think it makes sense.  Thoughts?

When someone has to manually create the rackspace-montoring-agent.cfg file, it has to be spot on. Right now if there is an extra space at the end of any line, it will fail with "Invalid Characters" when attempting to connect to the Agent API Endpoints.

Fri Apr 3 16:03:11 2015 ERR: Connection: 2001:4801:7902:1:0:a:6036:10:443 (2001:4801:7902:1:0:a:6036:10:443) -> Invalid characters 
Fri Apr 3 16:03:11 2015 INF: SRV:_monitoringagent._tcp.ord1.prod.monitoring.api.rackspacecloud.com -> Retrying connection in 56155ms

version=1.1.0-71, bundle_version=1.1.0-71

How to reproduce: 
Just add an extra space at the end of the monitoring_token or monitoring_id lines of rackspace-monitoring-agent.

System reproduced on: 
https://us.cloudcontrol.rackspacecloud.com/customer/902027/users/ef88adc6625343d4b47f48d6a2d355f8/next_gen_servers/IAD/d472e075-0b9f-4d3c-9f19-b29320bdfe5f 
OS: CentOS 6.5 
Linux vitruviant 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Maybe get the data and do a trim for spaces?

**Comment by rphillips** [comment]
release as 1.1.0-80
