### ISSUE TITLE
Pull CPU count

### ISSUE THREAD

**Issue by jacob0719** [virgo-agent-toolkit/rackspace-monitoring-agent#731]
There is a "ProcessorQueueLength" metric in windows_perfos check.  However; from Microsoft, this data needs to be correlated with the actual number of vCPUs.

> "For busy systems that experience processor utilization in the 80 to 90 percent range and use thread scheduling, the queue length should range from one to three threads per processor. For example, on a four-processor (4P) system, the expected range of processor queue length on a system with high CPU activity is 4 to 12."

Under the CPU check, it looks like there is a cpu_count item.  Can this also be added to the Windows_Perfos so the queue can be calculated?

**Comment by creationix** [comment]
FWIW, in luvit, you can get the number of virtual cores with `#(require('uv').cpu_info())`

**Comment by kaustavha** [comment]
Related PR #874

**Comment by kaustavha** [comment]
Related PR has been merged, closing this now. cc @jacob0719 @rjemanuele @rphillips @creationix
