### ISSUE TITLE
Agent Disconnect Support

### ISSUE THREAD

**Issue by rjemanuele** [virgo-agent-toolkit/rackspace-monitoring-agent#732]
In order to better support alerting on Agent Disconnects adding the minimum period found between checks listed in the manifest to the metrics sent up to the AEP would aid the monitoring core in alerting as quickly as possible.

For each set of metrics sent to the AEP two fields would be added to show the current minimum period between checks and the maximum jitter for running the checks.  An example would be if check 1 runs every 60s, check 2 runs every 120 secs, and check 3 runs every 30s then every metric submission by any check would send 30s as the minimum period.  We'd store this value every time the manifest gests updated for easy access.

This assists the monitoring core by including this value within the metric telescopes so the alerting pipeline (CEP) can have easy access to it.  Any older agents that would not include this value will alert if metrics have not been submitted for the maximum period.

**Comment by jirwin** [comment]
We'd actually be ok with a single field that is the sum of the two fields you proposed. We'll end up summing them on our end, and I can't think of a reason we'd need to know both. The jitter seems like it would be mostly static as well?

**Comment by rphillips** [comment]
Should we make this a metric or an attribute on the check_metrics.post RPC call?

**Comment by rjemanuele** [comment]
I vote for attribute.

**Comment by rphillips** [comment]
fixed
