### ISSUE TITLE
Win64: Service Stop Leaves a rogue rackspace-monitoring-agent process around

### ISSUE THREAD

**Issue by rphillips** [virgo-agent-toolkit/rackspace-monitoring-agent#742]
Version 1.9.5

#### Steps to Duplicate

1) Service Control Panel -> Click Stop
2) Agent still running in Processes

**Comment by rjemanuele** [comment]
we should probably just call process.exit(0)
https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/blob/luvi-up/winsvcwrap.lua#L288

**Comment by rphillips** [comment]
fixed in 19f583bbb4dd2
