### ISSUE TITLE
Win64: Rackspace Commandline -d dispatcher error

### ISSUE THREAD

**Issue by rphillips** [virgo-agent-toolkit/rackspace-monitoring-agent#744]
I 1) rebooted the server, 2) stopped the service, 3) then tried to run `rackspace-monitoring-agent.exe -d` from the command line and get this error.

![image](https://cloud.githubusercontent.com/assets/1963/8118933/a9b44d24-1057-11e5-86e5-b9d4d50ab248.png)

**Comment by rjemanuele** [comment]
That should be normal.

**Comment by rphillips** [comment]
ah ok. I think it worked before the reboot with the service stopped.
