### ISSUE TITLE
MS SQL Server Tests on Appveyor Require Admin Permisssions

### ISSUE THREAD

**Issue by rjemanuele** [virgo-agent-toolkit/rackspace-monitoring-agent#765]
There are 5 MSSQL check types.
* mssql_database
* mssql_buffer_manager
* mssql_sql_statistics
* mssql_memory_manager
* mssql_plan_cache

Of the 5, the mssql_database check uses the SQL interface to gather metrics about a particular database and therefore can use a specific SQL user's permissions for such a call.  This test is currently only simulated via a fixture but has the potential to be run on Appveyor if we load a database.

The other 4 are more problematic in testing.  Their metrics are gathered through the Powershell WMI get-counter interface and that requires local system administrative privileges.  As the agent is run using the system account this is no matter in production but makes testing tricky.

Solutions (in my personal preference):
* Convert the checks to ALWAYS use the SQL interface to gather metrics. https://msdn.microsoft.com/en-us/library/ms187743.aspx  It is unknown if this will produce all the metrics.
* Create an option for the checks to use the SQL interface to gather the metrics as above with the same constrains.
* Consider the fixture checks sufficient
* Run our own SQL machines to run the tests.

**Comment by rphillips** [comment]
I believe we have admin privileges on the appveyor boxes. that should alleviate some of the problems, right?

**Comment by rjemanuele** [comment]
@rphillips afaik we do not have local administration rights. We do have the SQL server SA account hence my comments about performing all the requests through the SQL interface if possible.

**Comment by rphillips** [comment]
I'm game for going with as much through the sql interface.

Their webpage [1] states: 

```Your build script has admin access to the build machine - you are free to do whatever you like to support your testing process: install new software, run services, even format disk drives :)```

[1] http://www.appveyor.com/docs/services-databases

**Comment by rjemanuele** [comment]
Hmmm.  Maybe we need to escalate the privilege when running the test.

**Comment by rjemanuele** [comment]
Thanks to Appveyor support, they corrected how we have to specify the service instance.
