### ISSUE TITLE
Reword the Confd warnings

### ISSUE THREAD

**Issue by rphillips** [virgo-agent-toolkit/rackspace-monitoring-agent#768]
```
Thu Jul 02 23:58:44 2015 INF: Confd -> reading files in /etc/rackspace-monitoring-agent.conf.d
Thu Jul 02 23:58:44 2015 ERR: Confd -> error reading dir /etc/rackspace-monitoring-agent.conf.d, nil
```

**Comment by stackedsax** [comment]
Where does conf.d live on a Windows box?  Should it warn the user at all if the agent just looks in the correct place for a Windows box?

**Comment by rjemanuele** [comment]
On Linux the configuration directory is /etc.  On Windows it is C:\ProgramData\Rackspace Monitoring\config.

Both the config file "rackspace-monitoring-agent.cfg" and conf.d directory "rackspace-monitoring-agent.conf.d" both belong under the configuration directory.

So on Windows conf.d yaml files belong in C:\ProgramData\Rackspace Monitoring\config\rackspace-monitoring-agent.conf.d\

**Comment by stackedsax** [comment]
So, surely we should just not check the /etc directory if the agent is installed on Windows, yes?

**Comment by rjemanuele** [comment]
That was a bug on 2.0.2 fixed in 2.0.5.

**Comment by kaustavha** [comment]
This pr 
https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/commit/788165a92a8ce278053e99177bd5b2d1515e0a60
fixes this issue. 
Should close.

**Comment by Speeddymon** [comment]
Looks like the PR was merged. Perhaps this bug can be closed?
