### ISSUE TITLE
implement tcp checks

### ISSUE THREAD

**Issue by rphillips** [virgo-agent-toolkit/rackspace-monitoring-agent#793]

**Comment by creationix** [comment]
Noit version at https://github.com/racker/noit/blob/ckdev/src/modules-lua/noit/module/tcp.lua

Initial luvit prototype at https://github.com/creationix/virgo-proto/blob/master/checks/tcp.lua

**Comment by creationix** [comment]
After extracting data from the live system, these appear to be the unique regular expressions found in tcp checks:

```lua
{ '', 'ssh', 'dkfdlkfjslf', '220 mail.slimta.org esmtp slimta.org mail submission agent', 
  'everything is fine', '.*', '200 ok', 'ssh-2.0-goanywhere services/2.0.2', '^/404/', 
  '220 mail.slimta.org esmtp slimta.org mail delivery agent', '(?s)^(2\\\\d\\\\d|425|530)', '^/220/', 
  '220\\\\.gsh1\\\\.groovesystems\\\\.com', 'filezilla server', '\\\\* ok.*', 
  'ok .* dovecot \\\\(ubuntu\\\\) ready', 'cloudmail.co.ke esmtp postfix', 
  'ok dovecot \\\\(ubuntu\\\\) ready', '2013', 'ssh-2.0-cerberusftpserver_6.0', 
  '^is not allowed to connect to this mysql$', '\\\\+ok.*', '1234', '\\\\* bye', 'asdf', 
  '(?s)^2\\\\d\\\\d', 'erty' }
```

**Comment by creationix** [comment]
Started adding pcre to luvi as a build option. https://github.com/luvit/luvi/tree/pcre2

**Comment by creationix** [comment]
Just released new luvit / lit / luvi with new "rex" module that implements PCRE using the lrexlib interface.

**Comment by creationix** [comment]
Finished core functionality to TCP check as part of https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/pull/830
