### ISSUE TITLE
Agent crash after AEP timeouts

### ISSUE THREAD

**Issue by ynachiket** [virgo-agent-toolkit/rackspace-monitoring-agent#893]
Though this stemmed from another AEP issue which was causing the agent handshakes to timeout, we did find out that the agent crashed.

https://gist.github.com/ynachiket/b3b5175372f7d7dcf7c1

This is a placeholder issue for this crash.

**Comment by ynachiket** [comment]
I was able to reproduce this error again and i think this is happening consistently across all our agents.
When i use a containerized agent the container dies and so this issue was highlighted. I am pretty sure this is happening in prod as well just that the agent comes back up in that situation:

This is a log similar to the one above .. in production: https://gist.github.com/ynachiket/f54291c7a25054120b16

Account: 879591

This graph that @jjbuchan pointed out also shows clearly that the agent connections are being dropped: https://www.evernote.com/shard/s357/sh/7876829f-60df-4f5e-bbe2-c64d7237a844/1ffbba2ec9eead8b

**Comment by rphillips** [comment]
make sure to try 2.2.7.... It should fix the issue with the crash. The handshake timeout is a different issue.
