### ISSUE TITLE
Rackspace Monitor agent update breaks lsync check

### ISSUE THREAD

**Issue by jmac05r1** [virgo-agent-toolkit/rackspace-monitoring-agent#916]
It appears that there was an update to the rackspace-monitoring-agent today, version 2.2.13. As a result quite a few tickets dealing with custom monitoring plugins are being generated, most notably CentOS 6.7 servers with the lsyncd-statu.sh plugin. These checks are exiting with a 127, command not found, status.

This seems to be due to a mis-configuration of the plugin path.

Correct Path:
/usr/lib/rackspace-monitoring-agent/plugins/lsyncd-status.sh

New Path:
/usr/lib/rackspace-monitoring-agent/plugins/usr/lib/rackspace-monitoring-agent/plugins/lsyncd-status.sh

Example error from the /var/log/rackspace-monitoring-agent.log file:

Wed Jan 06 02:15:11 PM 2016 INF: (plugin=/usr/lib/rackspace-monitoring-agent/plugins/lsyncd-status.sh, id=chCIHoRqzV, iid=idouNwQU3h) -> /usr/lib/rackspace-monitoring-agent/plugins/usr/lib/rackspace-monitoring-agent/plugins/lsyncd-status.sh: done (code=-127)

To test this we have done the following on a couple of servers:

mkdir -p /usr/lib/rackspace-monitoring-agent/plugins/usr/lib/rackspace-monitoring-agent/plugins/
cp /usr/lib/rackspace-monitoring-agent/plugins/lsyncd-status.sh /usr/lib/rackspace-monitoring-agent/plugins/usr/lib/rackspace-monitoring-agent/plugins/lsyncd-status.sh

This causes the check to complete with a 0 exit status and the alert clears.

This is a pretty big issue and is generating more and more tickets as servers update rackspace-monitoring-agent via yum-cron. If anyone can help us escalate this through proper channels it would be greatly appreciated. Thanks.

**Comment by rphillips** [comment]
the details.file should be the filename of the plugin instead of the path. It's documented here:

https://developer.rackspace.com/docs/cloud-monitoring/v1/developer-guide/#agent-plugin
