### ISSUE TITLE
sudo make install fails on Mac OS X El Capitan (10.11.4)

### ISSUE THREAD

**Issue by wolfdancer** [virgo-agent-toolkit/rackspace-monitoring-agent#933]
I am hoping this is some simple setting that I didn't do on the Mac or an easy fix. 

>  ~/work/rackspace-monitoring-agent (master)$ sudo make install [ruby-2.0.0p648]

install -m 777 build/rackspace-monitoring-agent /usr/bin/
install: /usr/bin//rackspace-monitoring-agent: Operation not permitted
make: *** [install] Error 71

**Comment by rphillips** [comment]
This is due to OSX's Security Integrity Protection. We don't have an installer for OSX, but you can run it out of your home directory.
