### ISSUE TITLE
is this wiki abandoned in favor of <developer.rackspace.com>?

### ISSUE THREAD

**Issue by joeashcraft** [virgo-agent-toolkit/rackspace-monitoring-agent#939]
The [Agent.mysql](https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/wiki/Agent.mysql) wiki page seems to be abandoned in favor of documents on [developer.rackspace.com](https://developer.rackspace.com/docs/rackspace-monitoring/v1/developer-guide/#agent-mysql).

If that's true, kindly hide the page, or add a conspicuous note of the fact.

**Comment by wolfdancer** [comment]
Thanks!  I have just cleaned it up and left the link to the official documentation: https://developer.rackspace.com/docs/rackspace-monitoring/v1/tech-ref-info/check-type-reference/
