### ISSUE TITLE
Agent is impotent without a resolver

### ISSUE THREAD

**Issue by Camisa** [virgo-agent-toolkit/rackspace-monitoring-agent#942]
The agent must fallback on IP when the resolver is unavailable or else registration cannot occur.  Cloud Servers are sometimes banned from Infrastructure name servers; in this case when agent registration cannot occur - the agent should not become a fish out of water.

**Comment by rphillips** [comment]
The agent needs a nameserver since we do not hardcode IPs within the agent. The agent will do a SRV record lookup, then use the host to resolve A and AAAA records to connect to port 443.
