### ISSUE TITLE
GLIBC build issue on CentOS 5.11

### ISSUE THREAD

**Issue by steve-white** [virgo-agent-toolkit/rackspace-monitoring-agent#949]
Hi, I'm having issues compiling the agent (master) on CentOS 5.11:
```
build/rackspace-monitoring-agent: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by build/rackspace-monitoring-agent)
build/rackspace-monitoring-agent: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by build/rackspace-monitoring-agent)

/lib64/libc.so.6
GNU C Library stable release version 2.5
```

Probably because the pre-built luvi / luvi-sigar which it pulls down were built against a newer OS. 
I've built luvi separately no problems, but how do I go about building luvi-sigar?
Also, how can I force the build to use my version instead of downloading the pre-built binary?

**Comment by rphillips** [comment]
Hey Steve, you can use [this](https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent-buildbot-builder) repo and run build.sh to build an agent from scratch.
