### ISSUE TITLE
Release updated .deb package

### ISSUE THREAD

**Issue by cfarquhar** [virgo-agent-toolkit/rackspace-monitoring-agent#959]
Can someone please advise what steps are necessary to release a new debian package that incorporates the two following PRs?:

 - Support punctuation in http credentials - https://github.com/luvit/luvit/pull/979
 - Add support for proxy authentication - https://github.com/virgo-agent-toolkit/luvit-request/pull/3

We're currently using a patched version, but I would like to revert to using upstream packages as soon as possible.

**Comment by rphillips** [comment]
We have an issue with some really old build machines... I'll get this out in the next release.

**Comment by rphillips** [comment]
This should be fixed with the 2.6.13 version of the agent.
