### ISSUE TITLE
Missing MySQL metric

### ISSUE THREAD

**Issue by inflatador** [virgo-agent-toolkit/rackspace-monitoring-agent#963]
Hello Monitoring devs,

This is a continuation of 

https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/issues/955

Per that PR, we have the following MySQL replication metrics available: 

replication.last_errno (Last_SQL_Errno) 
 replication.last_io_error (Last_IO_Error)
replication.last_io_errno (Last_IO_errno)

However, it does not look like we have a metric that covers Last_SQL_Error . (Presumably, it would be called replication.last_error or replication.last_sql_error). Are you able to create this metric?

Thanks for looking!

**Comment by harageth** [comment]
In case it was missed in chat this already exists.

replication.last_error is there. I suppose I should probably make sure that it is properly documented.

**Comment by inflatador** [comment]
I don't see it as an available metric when I try to create the alarm in Intelligence (agent version 2.16.4). I'll check in w/you once you're in the office.

**Comment by inflatador** [comment]
I'm seeing it now on a different device. Not sure what happened, but feel free to ignore this one.
